name: 'Deploy Staging'

on:
  push:
    tags:
      - '*'

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify Tag in Main
        id: verify_tag
        run: |
          TAG_NAME=${{ github.ref_name }}
          if git branch -r --contains "refs/tags/$TAG_NAME" | grep "origin/main"; then
            echo "Tag exists in main"
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "Tag does not exist in main. Exiting."
            exit 1
          fi

      - name: Verify Tag is Closest to HEAD of Main
        run: |
          TAG_NAME=${{ github.ref_name }}
          TAG_COMMIT_SHA=$(git rev-list -n 1 $TAG_NAME)
          LATEST_COMMIT_SHA=$(git rev-parse origin/main)

          # Find the most recent tag in the history of the main branch
          CLOSEST_TAG=$(git describe --tags --abbrev=0 $LATEST_COMMIT_SHA)

          if [ "$CLOSEST_TAG" = "$TAG_NAME" ]; then
            echo "tag_is_closest_to_main=true" >> $GITHUB_ENV
          else
            echo "Tag is not the closest to the HEAD of main. Exiting."
            exit 1
          fi
      
      - name: deploy
        run: |
          echo "Deploying staging ${{ github.ref_name }}"
          echo "Deploying staging ${{ github.sha }}"