name: 'Deploy Staging'

on:
  push:
    tags:
      - '*'

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify Tag in Main
        id: verify_tag
        run: |
          TAG_NAME=${{ github.ref_name }}
          if git branch -r --contains "refs/tags/$TAG_NAME" | grep "origin/main"; then
            echo "Tag exists in main"
            echo "tag_exists=true" >> $GITHUB_ENV
          else
            echo "Tag does not exist in main. Exiting."
            exit 1
          fi

      - name: Verify Latest Tag
        run: |
          TAG_NAME=${{ github.ref_name }}
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          if [ "$TAG_NAME" = "$LATEST_TAG" ]; then
            echo "tag_is_latest=true" >> $GITHUB_ENV
          else
            echo "Tag is not the latest. Exiting."
            exit 1
          fi
      
      - name: deploy
        run: |
          echo "Deploying staging ${github.ref_name}"
          echo "Deploying staging ${github.sha}"