apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ENVIRONMENT}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${REPOSITORY}
    targetRevision: ${BRANCH}
    path: charts
    helm: 
      values: |
${HELM_VALUES}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ${ENVIRONMENT_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
